feat: sending notification mail done
Vegari-1/NotificationService pull request #21
Opened 2022-07-28 07:54 UTC by nikolakabasaj

2022-07-28 12:22 UTC, djolewalker requested changes

2022-07-28 12:22 UTC, djolewalker commented on NotificationService/NotificationService.Service/EmailService.cs
> +        private MailMessage CreateMail(Model.Notification notification)
Mozemo ovo da pomerimo u konfiguracioni fajl?

2022-07-28 12:22 UTC, djolewalker commented on NotificationService/NotificationService.Repository.Interface/NotificationService.Repository.Interface.csproj
> +	  <PackageReference Include="MailKit" Version="3.3.0" />
Ne moras navoditi svuda, povucice dependency iz NotificationService.Model.csproj

2022-08-01 07:51 UTC, nikolakabasaj commented on NotificationService/NotificationService.Repository.Interface/NotificationService.Repository.Interface.csproj
> +	  <PackageReference Include="MailKit" Version="3.3.0" />
Ispravljeno

2022-08-01 07:52 UTC, nikolakabasaj commented on NotificationService/NotificationService.Service/EmailService.cs
> +        private MailMessage CreateMail(Model.Notification notification)
Moze, pomereno je

2022-08-01 14:25 UTC, djolewalker approved these changes

2022-08-02 06:50 UTC, merged